[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ieee_cis_fraud_detection"
version = "0.0.1"
description = "IEEE CIS Fraud Detection machine learning project."
authors = [
  { name = "Your name (or your organization/company/team)" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
requires-python = "~=3.10.0"
dependencies = [
    "pandas>=1.5.0",
    "pyarrow>=10.0.0",
    "loguru>=0.7.0",
    "python-dotenv>=0.21.0",
    "typer>=0.9.0",
    "tqdm>=4.65.0",
    "lightgbm>=4.0.0",
    "scikit-learn>=1.3.0",
    "dask>=2023.9.0",
    "distributed>=2023.9.0",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.1.0",
    "mkdocs>=1.5.0",
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
]


[tool.ruff]
line-length = 99
src = ["ieee_cis_fraud_detection"]
include = ["pyproject.toml", "ieee_cis_fraud_detection/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["ieee_cis_fraud_detection"]
force-sort-within-sections = true

